{
    L"1.2",         // Version
    0x0410, 
    L"Italian (Italiano)",
    {
        L"Sorgente:",
        L"Destinazione:",
        L"Etichetta:",
        L"File system:",
        L"Avvio",

        L"Seleziona o trascina la cartella qui",
        L"Seleziona destinazione ISO",
        L"da 0 a 128 caratteri per Etichetta Volume",

        L"ISO9660",
        L"ISO9660 + UDF 1.02 (DVD)",
        L"UDF 1.02",
        L"UDF 2.50 (BD/UHD)",

        L"&Lingua",
        L"&Integra nel menù contestuale",
        L"&Consenti Istanze multiple",
        L"&Mostra in Explorer quando finisce",
        L"&Chiudi quando finisce",
        L"&Mantieni in primo piano",
        L"&Traduzione",
        L"&Segnala problemi",
        L"&Linea di comando",
        L"&Informazioni su Folder2ISO...",
        
        L"&Theme",
        L"&Light",
        L"&Dark",
        L"&System",

        L"'%s' già esiste.\n\nVuoi sovrascrivelo?",
        L"ISO files (*.iso)\0*.iso\0\0",
        L"Questo programma è ad uso gratuito.\n\nAuthor: Young, Fred, Kira\nTranslator: Starix75",
    }
},