{
    L"1.1",         // Version
    0x0410, 
    L"Italian (Italiano)",
    {
        L"Sorgente:",
        L"Destinazione:",
        L"Etichetta:",
        L"File system:",
        L"Avvio",

        L"Selezione o trascina la cartella qui",
        L"Seleziona destinazione ISO",
        L"da 0 a 128 caratteri per Etichetta Volume",

        L"ISO9660",
        L"ISO9660 + UDF 1.02 (DVD)",
        L"UDF 1.02",
        L"UDF 2.50 (BD/UHD)",

        L"&Lingua",
        L"&Integra nel menù contestuale",
        L"&Allow multiple instances",
        L"&Reveal in Explorer when finished",
        L"&Chiudi quando finisce",
        L"&Mantieni in primo piano",
        L"&Traduzione",
        L"&Segnala problemi",
        L"&Lina di comando",
        L"&Riguardo a Folder2ISO...",

        L"'%s' già esiste.\n\nVuoi sovrascrivelo?",
        L"ISO files (*.iso)\0*.iso\0\0",
        L"QUesto programma è ad uso gratuito.\n\nAuthor: Young, Fred, Kira\nTranslator: Starix75",
    }
},